name: Add branch protection ruleset

on:
  push:
    paths:
      - ".github/repo-protection-ruleset.json"
      - ".github/workflows/protect-branch-rulesets.yml"
  workflow_dispatch:
jobs:
  create-branch-ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get DevOps Team ID
        id: fetch_bypass_team_id
        env:
          ACCESS_TOKEN: ${{ secrets.BLUE_ENERGY_TOKEN }}
          ORG_NAME: "EDBlueEnergy"
        run: |
          echo $(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/EDBlueEnergy/teams)
