name: Update branch protection rule
on:
  push:
    branches:
      - master
      - main
jobs:
  update-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update protection rules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_PATH: "branch-protection.config.json"
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d @$CONFIG_PATH \
            "https://api.github.com/repos/${{ github.repository }}/branches/azure/protection"
