name: Add branch protection ruleset

on:
  push:
    paths:
      - ".github/repo-protection-ruleset.json"
      - ".github/workflows/protect-branch-rulesets.yml"
  workflow_dispatch:
jobs:
  create-branch-ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add ruleset
        env:
          ACCESS_TOKEN: ${{ secrets.BLUE_ENERGY_TOKEN }}
          ORG_NAME: "EDBlueEnergy"
          CONFIG_PATH: ".github/repo-protection-ruleset.json"
        run: |
          repo_url="https://api.github.com/repos/$ORG_NAME/ruleset-test/rulesets"
          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token $ACCESS_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d @"$CONFIG_PATH" \
              "$repo_url"
