name: Update branch protection rule

on:
  push:
    paths:
      - ".github/feature-branch-ruleset.json"
      - ".github/workflows/protect-branch-rulesets.yml"
  workflow_dispatch:
jobs:
  update-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update protection rules
        env:
          ACCESS_TOKEN: ${{ secrets.BLUE_ENERGY_TOKEN }}
          CONFIG_PATH: ".github/feature-branch-ruleset.json"
          ORG_NAME: "EDBlueEnergy"
        run: |

          repo_name = "ruleset-test"
          repo_url = "https://api.github.com/repos/$ORG_NAME/$repo_name/rulesets"

          # Apply protection rules
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $ACCESS_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d @$CONFIG_PATH \
            "$repo_url"
