name: Add branch protection ruleset

on:
  push:
    paths:
      - ".github/feature-branch-ruleset.json"
      - ".github/workflows/protect-branch-rulesets.yml"
  workflow_dispatch:
jobs:
  create-branch-ruleset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get DevOps Team ID
        id: fetch_bypass_team_id
        env:
          ACCESS_TOKEN: ${{ secrets.BLUE_ENERGY_TOKEN }}
          ORG_NAME: "EDBlueEnergy"
        run: |
          # API_URL='https://api.github.com/orgs/$ORG_NAME/teams'
          # response=$(curl -L \
          # -H "Accept: application/vnd.github+json" \
          # -H "Authorization: token $ACCESS_TOKEN" \
          # -H "X-GitHub-Api-Version: 2022-11-28" \
          # $API_URL
          # )
          response=curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $ACCESS_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/$ORG_NAME/teams
          echo $response
          team_id=$(echo "$response" | jq -r '.id')

          echo "TEAM_ID=$team_id" >> $GITHUB_ENV

      # - name: Update protection rules
      #   env:
      #     ACCESS_TOKEN: ${{ secrets.BLUE_ENERGY_TOKEN }}
      #     CONFIG_PATH: ".github/feature-branch-ruleset.json"
      #     ORG_NAME: "EDBlueEnergy"
      #     TEAM_ID: ${{env.TEAM_ID}}
      #   run: |

      #     # Get ruleset json
      #     RULESET=$(cat $CONFIG_PATH)

      #     # Add bypass team
      #     UPDATED_RULESET=$(echo "RULESET" | jq --arg team_id "$TEAM_ID" '. + {'bypass_actors':[{"actor_id":$team_id,"actor_type":"Team","bypass_mode":"always"}]}')

      #     # Apply protection rules
      #     curl -L \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: token $ACCESS_TOKEN" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       -d "$UPDATED_RULESET" \
      #       https://api.github.com/repos/$ORG_NAME/ruleset-test/rulesets \
